USER_EMAIL_MIN_LEN = 3
USER_EMAIL_MAX_LEN = 254
USER_USERNAME_MIN_LEN = 5
USER_USERNAME_MAX_LEN = 20
USER_PASSWORD_MIN_LEN = 4
USER_PASSWORD_MAX_LEN = 100
USER_FIRST_NAME_MIN_LEN = 1
USER_FIRST_NAME_MAX_LEN = 50
USER_LAST_NAME_MIN_LEN = 1
USER_LAST_NAME_MAX_LEN = 50

ITEM_CONTENT_MIN_LEN = 1
ITEM_CONTENT_MAX_LEN = 500
ITEM_PREVIEW_MAX_LEN = 200

TAG_NAME_MIN_LEN = 1
TAG_NAME_MAX_LEN = 50
